# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 899fca607ae8201d007d90a228d5f1b5e702494a9d2fe224329baf391ecd3ee88a2387f0141c361956be226039732a46acc6dff54b33b5dfe48f62cfcbbc1274

test:
  secret_key_base: bc06632eb5a560b686cfedc5f5e61b075609c80c4b9cb956e7f72e3bead0fe7bc9d72d27515db23b6a744773ed9a48fcf063e8743e6278580f1219bd329fb84e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
